const mongoose = require('mongoose')
const SubscriptiontoDepthdata = mongoose.Schema(
    {
        t: { type: String },
        pp: { type: String },
        ml: { type: String },
        e: { type: String },
        tk: { type: String },
        ts: { type: String },
        ls: { type: String },
        ti: { type: String },
        c: { type: String },
        lp: { type: String },
        pc: { type: String },
        o: { type: String },
        h: { type: String },
        l: { type: String },
        uc: { type: String },
        lc: { type: String },
        ft: { type: String },
        ap: { type: String },
        v: { type: String },
        ltq: { type: String },
        ltt: { type: String },
        tbq: { type: String },
        tsq: { type: String },
        bp1: { type: String },
        sp1: { type: String },
        bp2: { type: String },
        sp2: { type: String },
        bp3: { type: String },
        sp3: { type: String },
        bp4: { type: String },
        sp4: { type: String },
        bp5: { type: String },
        sp5: { type: String },
        bq1: { type: String },
        sq1: { type: String },
        bq2: { type: String },
        sq2: { type: String },
        bq3: { type: String },
        sq3: { type: String },
        bq4: { type: String },
        sq4: { type: String },
        bq5: { type: String },
        sq5: { type: String },
        bo1: { type: String },
        so1: { type: String },
        bo2: { type: String },
        so2: { type: String },
        bo3: { type: String },
        so3: { type: String },
        bo4: { type: String },
        so4: { type: String },
        bo5: { type: String },
        so5: { type: String },
    })

module.exports = mongoose.model('SubscriptiontoDepthdata', SubscriptiontoDepthdata)
